"""Increase password_hash column size

Revision ID: 71757dc7f912
Revises: 262a7c003ef1
Create Date: 2025-02-04 11:11:56.768507

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '71757dc7f912'
down_revision = '262a7c003ef1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.Text(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('password_hash',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)

    # ### end Alembic commands ###
