"""empty message

Revision ID: ce8ced9add19
Revises: 33486eb1ec1f
Create Date: 2025-02-03 21:06:20.689865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce8ced9add19'
down_revision = '33486eb1ec1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('sight_words')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sight_words',
    sa.Column('word_id', sa.INTEGER(), sa.Identity(always=True, start=1, increment=1, minvalue=1, maxvalue=2147483647, cycle=False, cache=1), autoincrement=True, nullable=False),
    sa.Column('word', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('definition', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('grade', sa.TEXT(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('word_id', name='sight_words_pkey')
    )
    # ### end Alembic commands ###
