"""empty message

Revision ID: dd31ce7e7ca5
Revises: 3aba9a0cc11e
Create Date: 2025-01-28 14:31:09.757134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dd31ce7e7ca5'
down_revision = '3aba9a0cc11e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unlocked', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('achievements', schema=None) as batch_op:
        batch_op.drop_column('unlocked')

    # ### end Alembic commands ###
